# Generated by Django 4.2.14 on 2024-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorID', models.IntegerField()),
                ('pcID', models.IntegerField()),
                ('cpuCode', models.PositiveIntegerField()),
                ('cpuName', models.CharField(max_length=100)),
                ('cpuCost', models.PositiveIntegerField()),
                ('motherboardCode', models.PositiveIntegerField()),
                ('motherboardName', models.CharField(max_length=100)),
                ('motherboardCost', models.PositiveIntegerField()),
                ('memoryCode', models.PositiveIntegerField()),
                ('memoryName', models.CharField(max_length=100)),
                ('memoryCost', models.PositiveIntegerField()),
                ('gpuCode', models.PositiveIntegerField()),
                ('gpuName', models.CharField(max_length=100)),
                ('gpuCost', models.PositiveIntegerField()),
                ('ssdCode', models.PositiveIntegerField()),
                ('ssdName', models.CharField(max_length=100)),
                ('ssdCost', models.PositiveIntegerField()),
                ('caseCode', models.PositiveIntegerField()),
                ('caseName', models.CharField(max_length=100)),
                ('caseCost', models.PositiveIntegerField()),
                ('powerCode', models.PositiveIntegerField()),
                ('powerName', models.CharField(max_length=100)),
                ('powerCost', models.PositiveIntegerField()),
                ('coolerCode', models.PositiveIntegerField()),
                ('coolerName', models.CharField(max_length=100)),
                ('coolerCost', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('mentorID', 'pcID')},
            },
        ),
    ]
