from rest_framework import serializers

class PCEstimateSerializer(serializers.Serializer):
    costScope = serializers.CharField(required=False, allow_blank=True)
    cpuCodeBefore = serializers.CharField(required=False, allow_blank=True)
    cpuNameBefore = serializers.CharField(required=False, allow_blank=True)
    cpuCostBefore = serializers.CharField(required=False, allow_blank=True)
    motherboardCodeBefore = serializers.CharField(required=False, allow_blank=True)
    motherboardNameBefore = serializers.CharField(required=False, allow_blank=True)
    motherboardCostBefore = serializers.CharField(required=False, allow_blank=True)
    memoryCodeBefore = serializers.CharField(required=False, allow_blank=True)
    memoryNameBefore = serializers.CharField(required=False, allow_blank=True)
    memoryCostBefore = serializers.CharField(required=False, allow_blank=True)
    gpuCodeBefore = serializers.CharField(required=False, allow_blank=True)
    gpuNameBefore = serializers.CharField(required=False, allow_blank=True)
    gpuCostBefore = serializers.CharField(required=False, allow_blank=True)
    ssdCodeBefore = serializers.CharField(required=False, allow_blank=True)
    ssdNameBefore = serializers.CharField(required=False, allow_blank=True)
    ssdCostBefore = serializers.CharField(required=False, allow_blank=True)
    caseCodeBefore = serializers.CharField(required=False, allow_blank=True)
    caseNameBefore = serializers.CharField(required=False, allow_blank=True)
    caseCostBefore = serializers.CharField(required=False, allow_blank=True)
    powerCodeBefore = serializers.CharField(required=False, allow_blank=True)
    powerNameBefore = serializers.CharField(required=False, allow_blank=True)
    powerCostBefore = serializers.CharField(required=False, allow_blank=True)
    coolerCodeBefore = serializers.CharField(required=False, allow_blank=True)
    coolerNameBefore = serializers.CharField(required=False, allow_blank=True)
    coolerCostBefore = serializers.CharField(required=False, allow_blank=True)
